### ISSUE TITLE
Some files are missing in “ssl/common_utils”

### ISSUE THREAD

**Issue by Mayao15** [facebookresearch/luckmatters#10]
I tried to run the `bn_gen.py` script, but `common_utils.MultiRunUtil` seems to be missing which lead to errors. I managed to modify one of its function, `common_utils.MultiRunUtil.load_full_cfg` by myself to make the code usable. However, `common_utils.MultiRunUtil.load_omega_conf`, `common_utils.print_info` and maybe more remain undone. Please update the "ssl/common_utils" folder.

**Comment by yuandong-tian** [comment]
Thanks. Please install the common_utils package in https://github.com/yuandong-tian/tools2. Sorry for the inconvenience.

**Comment by Mayao15** [comment]
Thank you for your timely reply
