### ISSUE TITLE
"Init Teacher" never ends

### ISSUE THREAD

**Issue by Haoxiang-Wang** [facebookresearch/luckmatters#3]
I tried to run the `recon_multilayer.py` script with MNIST dataset. However, it got stuck at the "Init teacher" step for more than 2 hrs and didn't go to the next step. I wonder if the code enters an infinite loop?

input:
`python recon_multilayer.py --dataset mnist`
output:
`
cuda: 
Namespace(batchsize=64, bn=False, bn_affine=False, bn_before_relu=False, cmdline='recon_multilayer.py --dataset mnist', cross_entropy=False, d_output=0, data_d=20, data_std=10.0, dataset='mnist', eval_batchsize=64, init_multi=4, json_output=False, ks=[10, 15, 20, 25], load_teacher=None, lr={0: 0.01}, momentum=0.0, no_bias=False, no_sep=False, node_multi=10, normalize=False, num_epoch=40, num_iter=30000, num_trial=10, perturb=None, regen_dataset_each_epoch=False, same_dir=False, same_sign=False, save_dir='./', seed=1, signature='070519_161701_245908', stats_H=False, stats_w=False, teacher_bn=False, teacher_bn_affine=False, use_cnn=False, weight_decay=0)
ks: [10, 15, 20, 25]
d_output: 10
Init teacher..`
`

**Comment by yuandong-tian** [comment]
Sorry for (super) late reply. How many teacher nodes are you using? If the input dimension is small, then the initialization will never find distinct teachers and will enter into infinite loop.

**Comment by yuandong-tian** [comment]
Ok. I reproduce it. I never try running MNIST (only Gaussian and CIFAR10 are tested) :). Need to investigate.
