### ISSUE TITLE
Confusion about dyn_eps and dyn_reg in DirectPred

### ISSUE THREAD

**Issue by BannyStone** [facebookresearch/luckmatters#5]
Hi authors,

First of all, this is an issue on paper DirectPred. And I really like your DirectPred paper:)

There is confusion here:
In the README, dyn_reg is set to be 0.01 which is referred to as eps in Eq.18 in the paper.
However, in the corresponding code line, https://github.com/facebookresearch/luckmatters/blob/e621d9d8f564578bfa3553ceae69baddc077cf13/ssl/real-dataset/byol_trainer.py#L257, eps in Eq. 18 is represented by dyn_eps.

So which parameter, dyn_eps or dyn_reg, refers to the eps in Eq.18?

Thanks!

**Comment by yuandong-tian** [comment]
Thanks @BannyStone for the interest! I must have put a typo in the README file. Here is the original log file summary after 100 epochs and it uses `dyn_eps`. 

![image](https://user-images.githubusercontent.com/2973937/128905569-66ac4458-7db3-4a08-a530-630c037a0c50.png)

**Comment by BannyStone** [comment]
Thank you for your reply and for sharing the experiment log which is very helpful! I have been able to successfully reproduce a good result.
