### ISSUE TITLE
Theorem 1 proof: Understanding Self-Supervised Learning Dynamics without Contrastive Pairs

### ISSUE THREAD

**Issue by lihuiliullh** [facebookresearch/luckmatters#7]
May I know how you get equation 44? What is t here? 
My understanding is W_p is the parameter of the predictor. It is not a function of t. How can you take the derivative of W_p with respect to t?
Thanks for your work. It's a nice paper.

![image](https://user-images.githubusercontent.com/53407011/153697368-c0c34fe9-6ee2-4437-b553-35e7598d64d1.png)

**Comment by lihuiliullh** [comment]
@yuandong-tian

**Comment by yuandong-tian** [comment]
It is a function of $t$, since $W_p$ is also a trainable parameter.
