### ISSUE TITLE
torch.eig is deprecated for a long time and is being removed

### ISSUE THREAD

**Issue by kit1980** [facebookresearch/luckmatters#9]
PyTorch's torch.eig was deprecated since version 1.9 and is being removed by https://github.com/pytorch/pytorch/pull/70982. Please use the torch.linalg.eig function instead if you want your code to continue to work with the latest PyTorch.

Affected files:
https://github.com/facebookresearch/luckmatters/blob/main/luckmatter/test_multilayer.py
https://github.com/facebookresearch/luckmatters/blob/main/ssl/real-dataset/byol_trainer.py

**Comment by Lezcano** [comment]
For the first file, a much better way of writing `op_norm` is doing
```python
return torch.linalg.matrix_norm(A, ord=2).max().item()
```
Or using `linalg.svdvals` directly.
For the second file, you should use `linalg.eigh`, which is much better conditioned than `linalg.eig`. For the part where you don't use the eigenvectors, consider using `linalg.eigvalsh`.

**Comment by yuandong-tian** [comment]
Thanks for the information! Will change.
